#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# Runs clang-format-check on each clang-rename file.

mydir=$(dirname $0)

cdup=$(git rev-parse --show-cdup)

[ -n "$cdup" ] && cd $cdup

for file in $(find tools/clang/lib/Tooling/Refactoring/Rename/ tools/clang/tools/clang-rename/ -type f)
do
	case $file in
	*.cpp|*.h)
		$mydir/clang-format-check $file || exit 1
		;;
	esac
done

# vim:set shiftwidth=4 softtabstop=4 expandtab:
