#!/bin/bash
# 
#   darcs2git
#  
#   Copyright (c) 2007 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

usage()
{
	echo "usage: $0 <source darcs repo> <target git repo>"
	echo
	echo "example: '$0 ../darcs/test .' - this will create a git repo in"
	echo "                                the ./test dir"
}

die()
{
	echo "$0: $@"
	exit 1
}

if [ "$#" != 2 ]; then
	usage
	exit 1
fi

src=$1
target=$2

[ -d "$src" ] || die "source dir does not exist!"

cd $src
src=`pwd`

myname=`basename $src`

cd - >/dev/null

[ -d "$target" ] || die "target dir does not exist!"

cd $target
target=`pwd`

myroot=`mktemp -d`
mygitroot=`mktemp -d`
rmdir $mygitroot

cd $myroot

cat > config << EOF
[DEFAULT]
verbose = True
patch-name-format=%(revision)s

[$myname]
source = darcs:test
target = git:test

[darcs:test]
subdir = darcs
repository = $src

[git:test]
subdir = git
repository = $mygitroot
encoding = latin2
EOF

tailor --configfile config

cd $target
git clone $mygitroot $myname
rm -rf $myroot $mygitroot
