#!/bin/bash
# 
#   darcs2git
#  
#   Copyright (c) 2007 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

usage()
{
	echo "usage: $0 <source darcs repo> <target git repo>"
	echo
	echo "the previous contents of the target directory will be removed if"
	echo "there is any!"
}

if [ "$#" != 2 ]; then
	usage
	exit 1
fi

myname=`basename $1`

myroot=`mktemp -d`

cd $myroot

cat > config << EOF
[DEFAULT]
verbose = True
patch-name-format=%(revision)s

[$myname]
source = darcs:test
target = git:test

[darcs:test]
subdir = darcs
repository = $1

[git:test]
subdir = git
repository = $2
EOF

rm -rf $2 darcs git $myname.*
tailor --configfile config

cd - >/dev/null
rm -rf $myroot
