#!/bin/bash
#
# Copyright 2019 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# This script backs up your Google calendar.  To use, run 'backup' first
# interactively.

cd $(dirname $0)
if ! ~/git/vmexam/google/calendar/backup -n; then
    echo "backup failed, please run manually." |send-email -f $(git config user.email|sed "s/.*@/$(hostname)@/") -s "google calendar backup error" $(git config user.email)
    exit
fi

cp ~/.google-calendar/calendar.json .

git add calendar.json && git commit --quiet -m "$(date +%Y-%m-%d)" >/dev/null

# vim:set shiftwidth=4 softtabstop=4 expandtab:
