#!/bin/bash
#
# Copyright 2019 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

# This script backs up your Google calendar.  To use, run 'backup' first
# interactively.

cd $(dirname $0)
if ! ~/git/vmexam/google/calendar/backup -n; then
    echo "backup failed, please run manually." |~/bin/pymail -r $(git config user.email|sed "s/.*@/$(hostname)@/") -s "google calendar backup error" $(git config user.email)
    exit
fi

cp ~/.google-calendar/calendar.json .

git add calendar.json && git commit --quiet -m "$(date +%Y-%m-%d)"

# vim:set shiftwidth=4 softtabstop=4 expandtab:
