#!/bin/bash
#
# Copyright 2019 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# This script backs up your Google contacts.  To use, run 'backup' first
# interactively.

cd $(dirname $0)
if ! ~/git/vmexam/google/contacts/backup -n; then
    echo "backup failed, please run manually." |~/bin/pymail -r $(git config user.email|sed "s/.*@/$(hostname)@/") -s "google contacts backup error" $(git config user.email)
    exit
fi

cp ~/.config/google-contacts/contacts.json .

git add contacts.json && git commit --quiet -m "$(date +%Y-%m-%d)"

# vim:set shiftwidth=4 softtabstop=4 expandtab:
