#!/bin/bash
#
# Copyright 2020 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# This script backs up data using rsync from various machines.

case $1 in
vostro)
    mkdir -p vostro
    cd vostro
    if ! rsync -avP --delete-after --exclude=workdir --exclude=.ccache --delete-excluded -x / .; then
        echo "rsync failed giving up"
        exit 1
    fi
    ;;
plug3-root)
    cd plug3-root
    if ! rsync -avP --delete-after -x plug.vmiklos.hu:/ .; then
        echo "rsync failed giving up"
        exit 1
    fi
    ;;
plug3-home)
    cd plug3-home
    # Restore: rsync -avP ./ plug.vmiklos.hu:/home
    if ! rsync -avP --delete-after -x --exclude=plug2 plug.vmiklos.hu:/home/ .; then
        echo "rsync failed giving up"
        exit 1
    fi
    ;;
plug3-boot-efi)
    cd plug3-boot-efi
    if ! rsync -avP --delete-after -x plug.vmiklos.hu:/boot/efi/ .; then
        echo "rsync failed giving up"
        exit 1
    fi
    ;;
wilson)
    cd wilson
    if ! ssh wilson.vmiklos.hu 'cd /var/lib/nextcloud; ./backup.sh'; then
        echo "sqldump failed, giving up"
        exit 1
    fi
    if ! rsync -avP --delete-after -x --exclude=swapfile wilson.vmiklos.hu:/ .; then
        echo "rsync failed giving up"
        exit 1
    fi
    ;;
genesis)
    cd genesis
    if ! rsync -avP --delete-after -x genesis.vmiklos.hu:/etc/teleirc/ .; then
        echo "rsync failed giving up"
        exit 1
    fi
    ;;
*)
    echo "error: missing machine"
    echo "state of backups:"
    for i in */DATE
    do
        date=$(cat $i)
        printf "%16s: " $(dirname $i)
        if [ -z "$date" ]; then
            echo "no backup yet"
        else
            cat $i
        fi
    done
    exit 1
;;
esac

date -Iseconds > DATE

# vim:set shiftwidth=4 softtabstop=4 expandtab:
