#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# This script runs chkworld and mails the result if there was any output.

tmp=$(mktemp)
verbose=f

timeout 1m ssh dev-downloads "sh -c 'cd /srv/git/lo-linux-dbgutil-daily.git; git log -1 --pretty=format:%s%n'" &> $tmp

if ! cat $tmp |grep -q "$(date +%Y-%m-%d)"; then
    cat $tmp |~/bin/pymail -r "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "lo-daily.git: outdated for $(date +%Y-%m-%d)" $(git config user.email)
elif [ "$verbose" == "t" ]; then
    cat $tmp |~/bin/pymail -r "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "lo-daily.git: up to date for $(date +%Y-%m-%d)" $(git config user.email)
fi

rm -f $tmp

# vim:set shiftwidth=4 softtabstop=4 expandtab:
