#!/usr/bin/env python

# Dump script which just tries to uncomment each include to see if it causes a
# build failure.
#
# Example: find-unneeded-includes 'make -sr build -j4' source/filter/ww8/rtfsdrexport.cxx

import sys, os

def comment_line(lines, linenum):
	lines[linenum] = "//%s" % lines[linenum]
	with open(srcfile, "w") as sock:
		sock.write("".join(lines))
	return lines

def uncomment_line(lines, linenum):
	assert lines[linenum][:2] == "//"
	lines[linenum] = lines[linenum][2:]
	with open(srcfile, "w") as sock:
		sock.write("".join(lines))
	return lines

buildcmd = sys.argv[1]
srcfile = sys.argv[2]

sock = open(srcfile)
lines = sock.readlines()
sock.close()

for i, line in enumerate(lines):
	if not line.startswith("#include"):
		continue
	lines = comment_line(lines, i)
	if os.system(buildcmd) != 0:
		lines = uncomment_line(lines, i)
