virt-install \
	--name=frugalware \
	--arch=x86_64 \
	--vcpus=1 \
	--ram=1024 \
	--os-variant=linux2016 \
	--connect=qemu:///system \
	--network network=default \
	--cdrom=/home/vmiklos/virt/frugalware/frugalware.iso \
	--disk path=/home/vmiklos/virt/frugalware/frugalware.img,size=20 \
	--accelerate \
	--vnc \
	--noautoconsole
