#!/bin/bash -e
#
# Copyright 2018 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

style-check-files
if git-review -R; then
    rev=$(git rev-parse HEAD)
    host=$(git config -f .gitreview gerrit.host)
    port=$(git config -f .gitreview gerrit.port)
    ssh -p $port $host gerrit review --code-review=2 $rev
fi

# vim:set shiftwidth=4 softtabstop=4 expandtab:
