#!/bin/bash -e
#
# Copyright 2018 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

if [ -e .gitreview ]; then
    # Gerrit
    style-check-files
    if git-review -R; then
        rev=$(git rev-parse HEAD)
        host=$(git config -f .gitreview gerrit.host)
        port=$(git config -f .gitreview gerrit.port)
        ssh -p $port $host gerrit review --code-review=2 $rev
    fi
    exit 0
fi

if [ -e .github ]; then
    # GitHub
    BRANCH=$(git symbolic-ref HEAD|sed 's|refs/heads/||')
    REMOTE=$(git config branch.$BRANCH.remote)
    if git rev-parse --quiet --verify $REMOTE/private/$USER/$BRANCH >/dev/null; then
        # PR is open, just update it.
        git push -f $REMOTE HEAD:private/$USER/$BRANCH
    else
        # Open a new PR.
        git push $REMOTE HEAD:private/$USER/$BRANCH
        git branch private/$USER/$BRANCH
        gh pr create --base $BRANCH --head private/$USER/$BRANCH --fill | tee .git/gh-pr-create.log
        gh pr merge --rebase --auto $(cat .git/gh-pr-create.log)
        git branch -D private/$USER/$BRANCH
    fi
    exit 0
fi

# vim:set shiftwidth=4 softtabstop=4 expandtab:
