#!/usr/bin/env python

import sys, os

sock = os.popen("git log --date=short --name-only %s" % " ".join(sys.argv[1:]))

author = date = None
body = []
files = []

def dump_entry():
	global author, date, body, files
	print "%s  %s\n" % (date, author)
	i = 0
	while i < len(files):
		line = ""
		if i == 0:
			line += "\t* "
		else:
			line += "\t  "
		line += files[i]
		if i + 1 == len(files):
			line += ":"
		else:
			line += ","
		print line
		i += 1
	for i in body:
		print "\t  %s" % i
	print
	body = []
	files = []

while True:
	line = sock.readline()
	if not line:
		break
	if line.startswith("commit "):
		continue
	if line.startswith("Author:"):
		author = line[8:-1].replace("<", " <")
	elif line.startswith("Date:"):
		date = line[8:-1]
	elif line.startswith("    "):
		body.append(line[4:-1])
	elif line == "\n" and len(files):
		dump_entry()
	elif line != "\n":
		files.append(line[:-1])
sock.close()
dump_entry()
