#!/bin/bash -e
#
# Copyright 2020 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

if [ -e .github ]; then
    # GitHub
    BRANCH=$(git symbolic-ref HEAD|sed 's|refs/heads/||')
    REMOTE=$(git config branch.$BRANCH.remote)
    if git rev-parse --quiet --verify $REMOTE/private/$USER/$BRANCH >/dev/null; then
        # PR is open, just update it.
        git push -f $REMOTE HEAD:private/$USER/$BRANCH
    else
        # Open a new PR.
        git push $REMOTE HEAD:private/$USER/$BRANCH
        git branch private/$USER/$BRANCH
        gh pr create --base $BRANCH --head private/$USER/$BRANCH --fill
        git branch -D private/$USER/$BRANCH
    fi
    exit 0
fi

# vim:set shiftwidth=4 softtabstop=4 expandtab:
