#!/bin/sh

# NOTE: you should list all Ccs in one line, git-send-email otherwise will ignore the 2nd.. lines

git-send-email --envelope-sender "Miklos Vajna <vmiklos@frugalware.org>" --from "Miklos Vajna <vmiklos@frugalware.org>" --to "Junio C Hamano <gitster@pobox.com>" *.patch
