[package]
name = "mutt-imap-lister"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
home = "0.5.11"
imap = "2.4.1"
native-tls = "0.2.14"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
