CXXFLAGS += $(shell pkg-config --cflags libwpd-0.8)
LDFLAGS += $(shell pkg-config --libs libwpd-0.8)
CXXFLAGS += $(shell pkg-config --cflags libwpd-stream-0.8)
LDFLAGS += $(shell pkg-config --libs libwpd-stream-0.8)
all: foo
