#!/bin/bash
#
# Copyright 2016 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# This script runs chkworld and mails the result if there was any output.

tmp=$(mktemp)

~/git/vmexam/opensuse/chkworld &> $tmp

if [ -s $tmp ]; then
    cat $tmp |~/bin/pymail -r "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "OSC TODO for `date +%Y%m%d`" $(git config user.email)
fi

rm -f $tmp

# vim:set shiftwidth=4 softtabstop=4 expandtab:
