[package]
name = "git-ls-projects"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
glob = "0.3.1"
home = "0.5.9"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"
