[package]
name = "exec-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
home = "0.5.11"
isahc = "1.7.2"
lazy_static = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
toml = "0.9.5"
