#!/usr/bin/python
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

import json
import os
import subprocess

server = "logerrit"
project = "core"
# server = "opensuse-gerrit"
# project = "test"

sock = subprocess.Popen(["ssh", server, "gerrit", "stream-events"], stdout=subprocess.PIPE, bufsize=1)

for line in iter(sock.stdout.readline, b''):
    event = json.loads(line)

    if event['type'] != "comment-added":
        continue
    if event['change']['owner']['username'] != os.environ['USER']:
        continue
    if event['change']['project'] != project:
        continue
    if event['change']['branch'] != "master":
        continue
    if 'approvals' not in event.keys():
        continue
    if len([approval for approval in event['approvals'] if approval['type'] == "Verified" and approval['value'] == "1"]) != 1:
        continue

    rev = event['patchSet']['revision']
    cmd = "ssh " + server + " gerrit review -s " + rev
    print(cmd)
    os.system(cmd)

sock.communicate()

# vim:set shiftwidth=4 softtabstop=4 expandtab:
