json: json.cc Makefile
	g++ -std=c++11 -o json json.cc

json-array-read: json-array-read.cc Makefile
	g++ -std=c++11 -o json-array-read json-array-read.cc

poco: poco.cc Makefile
	g++ -std=c++11 -o poco poco.cc -lPocoFoundation -lPocoJSON

crtp: crtp.cc Makefile
	g++ -std=c++11 -o crtp crtp.cc

python-filter: python-filter.cxx Makefile
	g++ -std=c++11 -o python-filter python-filter.cxx

python-map: python-map.cxx Makefile
	g++ -std=c++11 -o python-map python-map.cxx

scope-guard: scope-guard.cxx Makefile
	g++ -std=c++11 -o scope-guard scope-guard.cxx
