[package]
name = "skel"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.10", features = [] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile.release]
lto = true
opt-level = "z"
strip = true
codegen-units = 1
panic = "abort"
