#!/bin/bash

name="$1" # e.g. unit-base
if [ -z "$name" ]; then
    echo "missing parameter: test name"
    exit 1
fi

limit="$2"
count=0
while true
do
    count=$((count+1))

    (cd test; ./run_unit.sh --test-name $name.la --log-file $name.log --trs-file $name.trs --color-tests yes --enable-hard-errors yes --expect-failure no -- ./$name.la)
    ./coolwsd --disable-cool-user-checking --cleanup
    if ! grep -q FAIL test/$name.trs; then
        break
    fi

    if [ -z "$limit" ] || [ "$count" -eq "$limit" ]; then
        break
    fi
done

# vi:set shiftwidth=4 expandtab:
