[package]
name = "mutt-display-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytelines = "2.5.0"
time = { version = "0.3.41", features = ["formatting", "local-offset", "parsing"] }
