[application]

[web.app]

# HTML title tag content
title = "child-slide"

base_path = "/pages/child-slide/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
