#!/usr/bin/env bash
#
# Copyright 2019 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

#
# Chart number of addr:housenumber tags in an area.
#
# Expected:
#
# 1) Each input file is an output of the street-housenumbers.txt query.
# 2) The filename of the input file is the date of the data.
#
# Output is again a csv file that can be charted easily by spreadsheet
# software.
#
# Example: ./chart-addr-housenumber 2015-*.csv > chart.csv
#

for i in "$@"
do
    key=$(basename $i .csv)
    value=$(grep -v ^@ "$i" |wc -l)
    echo $key$'\t'$value
done

# vim:set shiftwidth=4 softtabstop=4 expandtab:
