#!/usr/bin/env bash
#
# Copyright 2020 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

#
# Copy exported keypad mapper traces from phone (in a termux session) to my NAS.
#

year="$(date +%Y)"
cd storage/shared/Documents/
scp ${year}* vmiklos@plug.vmiklos.hu:feltoltes/

# vim:set shiftwidth=4 softtabstop=4 expandtab:
