#!/usr/bin/env python3
#
# Copyright 2019 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

from urllib.request import urlopen
import sys

url = "http://overpass-api.de/api/interpreter"

sock = open(sys.argv[1])
query = sock.read()
sock.close()

sock = urlopen(url, bytes(query, "utf-8"))
buf = sock.read()
sock.close()

sys.stdout.write(buf.decode("utf-8"))

# vim:set shiftwidth=4 softtabstop=4 expandtab:
