#!/usr/bin/env python3
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

from urllib.request import urlopen
from urllib.request import HTTPError
import sys

url = "http://overpass-api.de/api/interpreter"

sock = open(sys.argv[1])
query = sock.read()
sock.close()

sock = urlopen(url, bytes(query, "utf-8"))
buf = sock.read()
sock.close()

sys.stdout.write(buf.decode("utf-8"))

# vim:set shiftwidth=4 softtabstop=4 expandtab:
