#!/bin/bash -ex

# See http://www.mplayerhq.hu/DOCS/HTML/en/menc-feat-vcd-dvd.html
# Assuming PAL DVD and a movie where 16:9 is a better approximation than 4:3.

file=$1

if [ -n "$2" ]; then
	ratio=$2
else
	ratio="16/9"
fi

mencoder -oac lavc -ovc lavc -of mpeg -mpegopts format=dvd:tsaf -vf expand=:::::$ratio,scale=720:576,harddup -srate 48000 -af lavcresample=48000 -lavcopts vcodec=mpeg2video:vrc_buf_size=1835:vrc_maxrate=9800:vbitrate=5000:keyint=15:vstrict=0:acodec=ac3:abitrate=192:aspect=$ratio:threads=2 -lavdopts threads=2 -ofps 25 -o $file.mpg $file

# http://www.salixos.org/wiki/index.php/How_to_create_a_video_DVD_from_the_command_line
# Again, assuming PAL

dvdauthor -o $file-dvd/ -t $file.mpg
VIDEO_FORMAT=PAL dvdauthor -o $file-dvd/ -T
mkisofs -dvd-video -o $file.iso $file-dvd/
