#!/bin/sh -x

if [ -z "$*" ]; then
	echo "usage: $0 out.pdf *.jpg"
	exit 1
fi

outlist=""
out=$1
shift
for i in $*
do
	convert $i `basename $i .jpg`.pnm
	pnmtops `basename $i .jpg`.pnm >`basename $i .jpg`.ps
	rm `basename $i .jpg`.pnm
	outlist="$outlist `basename $i .jpg`.ps"
done

gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$out $outlist
rm $outlist
