#!/bin/sh

if [ -z "$*" ]; then
	echo "usage: $0 out.pdf *.jpg"
	exit 1
fi

outlist=""
out="$1"
shift
c=0
for i in "$@"
do
	convert "$i" $c.pnm
	pnmtops $c.pnm >$c.ps
	rm $c.pnm
	outlist="$outlist $c.ps"
	c=$(($c+1))
done

gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$out" $outlist
rm $outlist
