#!/bin/bash

# a simple script to convert any video to the SVCD format

mencoder -oac lavc -ovc lavc -of mpeg -mpegopts format=xsvcd -vf \
scale=480:576,harddup -srate 44100 -af lavcresample=44100 -lavcopts \
vcodec=mpeg2video:mbd=2:keyint=15:vrc_buf_size=917:vrc_minrate=600:vbitrate=2500:vrc_maxrate=2500:acodec=mp2:abitrate=224 \
-ofps 25 -o $1.mpg $*

vcdimager -t svcd -c $1.cue -b $1.bin --volume-count=0 --volume-number=0 $1.mpg
