[package]
name = "hyphen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyphen-sys = { path = "../hyphen-sys" }
libc = "0.2.112"
thiserror = "1.0.30"
