#!/usr/bin/env python3
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Script to give the compiler arguments for a source file.

import json
import os
import re
import sys


def getRepoRoot(inputFile):
    inputDir = os.path.dirname(inputFile)
    cwd = os.getcwd()
    os.chdir(inputDir)
    sock = os.popen("git rev-parse --show-cdup")
    cdup = sock.read().strip()
    sock.close()
    os.chdir(cdup)
    ret = os.getcwd()
    os.chdir(cwd)
    return ret


def emitGbuildCompilerArgs(root, inputFile):
    sock = open(os.path.join(root, "compile_commands.json"))
    commands = json.load(sock)
    for command in commands:
        if command['file'] == inputFile:
            args = command['command']
            args = args.replace(inputFile, '')
            print(args)
            break
    sock.close()


def main(argv):
    inputFile = argv[0]
    root = getRepoRoot(inputFile)
    if os.path.exists(os.path.join(root, "solenv")):
        # It's a LibreOffice gbuild checkout.
        emitGbuildCompilerArgs(root, inputFile)
    else:
        # It's something else.
        print("-std=c++1y")

if __name__ == "__main__":
    main(sys.argv[1:])

# vim:set shiftwidth=4 softtabstop=4 expandtab:
