#!/usr/bin/env python3
#
# Copyright 2018 Miklos Vajna
#
# SPDX-License-Identifier: MIT

import json
import os
import re
import sys
import csv


# Searches for a string (e.g. name or email) in the MCM db.
def searchInMcm(mcm, query):
    for member in mcm:
        if query in member:
            return True
    return False


def readMcm():
    mcm = []
    with open('current_members.txt') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            # id, given, family, email, rest
            mcm.append("{} {} <{}>".format(row[1], row[2], row[3]))
    return sorted(set(mcm))

# Filters git shortlog about, hiding already existing TDF members.
def main(argv):
    git = True
    company = ""
    if len(argv) and argv[0] == "--company":
        company = argv[1]
    if len(argv) and argv[0] == "--qa":
        git = False
    config = json.load(open("git-mcmshortlog.json"))
    ignoreNames = [n["name"] for n in config["ignoreNames"]]
    emailMap = config["emailMap"]
    if git:
        sock = os.popen("git shortlog -s -n -e --since=6.months.ago")
    else:
        sock = open("qa.csv")
    mcm = readMcm()
    while True:
        line = sock.readline().strip()
        if not line:
            break
        if git:
            if not ('\t' in line):
                continue
            commits, nameEmail = line.split('\t')
            if int(commits) < 10 and not company:
                # Less then 10 recent commits -> assume it's the not interesting
                # long tail.
                break
            name = re.sub(r'(.*) <(.*)>', r'\1', nameEmail)
            email = re.sub(r'(.*) <(.*)>', r'\2', nameEmail)
        else:
            if not line:
                break
            name, email = line.split(", ")

        if name in ignoreNames:
            continue
        if company and company not in email:
            continue

        if email in emailMap.keys():
            email = emailMap[email]
        if searchInMcm(mcm, email):
            # Found by email.
            continue

        if searchInMcm(mcm, name):
            # Found by name.
            continue

        print(line)
    sock.close()

if __name__ == "__main__":
    main(sys.argv[1:])

# vim:set shiftwidth=4 softtabstop=4 expandtab:
