#!/usr/bin/env python3
#
# Copyright 2019 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# Prints a short version of
# <https://en.wikipedia.org/wiki/Little_Red_Riding_Hood>, except it shuffles
# the actors.
# TODO don't hardcode language to be Hungarian.

import random

# From <http://mek.oszk.hu/02100/02115/html/4-642.html>.
text = """{Actor04} bort és kalácsot visz a beteg {Actor11}. Útközben összetalálkozik
{Actor22}, és az rábeszéli, hogy virágot is vigyen. Míg {Actor00} virágot szed,
{Actor20} elnyargal {Actor13}, megeszi és magára öltve hálóköntösét és
hálósapkáját, befekszik az ágyába. Nemsokára megérkezik {Actor00}, és
megkérdezi, hogy miért olyan nagy a füle, szeme, szája. {Actor24} válaszai: a)
azért, hogy jobban halljalak, b) azért, hogy jobban lássalak, c) azért, hogy
könnyebben bekaphassalak/vagy felszólítja, hogy feküdjön mellé. {Actor04}
nekikészülődik, de irtózik és kérdéseket tesz fel: miért olyan nagy/vagy szőrös
a lába, a keze, a szája stb., {Actor20} bekapja. Az arrajáró {Actor35}
meghallja {Actor20} erős horkolását, bemegy, felvágja a hasát, és {Actor00} és
{Actor10} elevenen kisétál belőle. A hasat megtöltik kaviccsal. {Actor24}
elpusztul."""

actors = [
    [
        'Piroska',
        'Piroskának',
        'Piroskával',
        'Piroskához',
        'Piroska',
        'Piroska'
    ],
    [
        'a nagymama',
        'nagymamának',
        'a nagymamával',
        'a nagymamához',
        'A nagymama',
        'nagymama'
    ],
    [
        'a farkas',
        'farkasnak',
        'a farkassal',
        'a farkashoz',
        'A farkas',
        'farkas'
    ],
    [
        'a vadász',
        'vadásznak',
        'a vadásszal',
        'a vadászhoz',
        'A vadász',
        'vadász'
    ]
]

# Maps original actors to actors in the current run.
currentActors = list(range(len(actors)))

random.shuffle(currentActors)

for actor in range(len(actors)):
    for variant in range(len(actors[0])):
        fro = "{Actor" + str(actor) + str(variant) + "}"
        to = actors[currentActors[actor]][variant]
        text = text.replace(fro, to)

print(text)

# vim:set shiftwidth=4 softtabstop=4 expandtab:
