#!/bin/bash
# 
# Copyright 2023 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# make-container-tarball: create an archive that can be imported into podman

[ -e /usr/lib/frugalware/fwmakepkg ] && . /usr/lib/frugalware/fwmakepkg

[ -z "$arch" ] && arch=$(uname -m)
[ -z "$ver" ] && ver=$(date +%Y%m%d)

# makepkg configuration
[ -f /etc/makepkg.conf ] && source /etc/makepkg.conf

CHROOTDIR="fwchroot-$ver-$arch/"

chroot_umount() {
    echo "Attempting to umount chroot directories..."
    umount $CHROOTDIR/proc >/dev/null
    umount $CHROOTDIR/sys >/dev/null
    umount $CHROOTDIR/var/cache/pacman-g2 >/dev/null
    if [ $? != 0 ]; then
        echo "An error occurred while attempting to umount chroot directories."
        exit 1
    fi
    echo "Successfully umounted chroot directories."
}

chroot_mount() {
    echo "Attempting to mount chroot directories..."
    mount -t proc none $CHROOTDIR/proc >/dev/null
    mount -t sysfs none $CHROOTDIR/sys >/dev/null
    mount -o bind /var/cache/pacman-g2 $CHROOTDIR/var/cache/pacman-g2 >/dev/null
    if [ $? != 0 ]; then
        echo "An error occurred while attempting to mount chroot directories."
        exit 1
    fi
    echo "Successfully mounted chroot directories."
}

if [ $(id -u) != 0 ]; then
    echo "Building the chroot as an unprivileged user is not possible."
    exit 1
fi

mkdir -p $CHROOTDIR/{etc,proc,sys,var/cache/pacman-g2,var/tmp/fst,tmp,var/log}

chroot_mount

echo "Building chroot environment"
# curl, otherwise https is hard to do
pacman -Syf $COREPKGS curl -r "$CHROOTDIR" --noconfirm
if [ $? != 0 ]; then
    echo "Failed to build chroot environment."
    chroot_umount
    exit 1
fi
    
chroot_umount
rm $CHROOTDIR/dev/*
cd $CHROOTDIR
tar cvjf ../frugalware-$ver-$arch.tar.bz2 .
cd ..
rm -rf $CHROOTDIR

# vim:set shiftwidth=4 softtabstop=4 expandtab:
