#!/usr/bin/env bash
#
# Copyright 2020 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

cd $(dirname $0)
date="$(date +%Y-%m-%d)"
./overpass_query.py street-housenumbers-hungary.txt > "${date}.csv"
./count.py "${date}.csv" > "${date}.count"

# Clean up older (than 7 days), large .csv files.
find . -type f -name "*.csv" -mtime +7 -exec rm -f {} \;

# vim:set shiftwidth=4 softtabstop=4 expandtab:
