#!/usr/bin/env bash
#
# Copyright 2020 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

cd $(dirname $0)
date="$(date +%Y-%m-%d)"
./overpass_query.py street-housenumbers-hungary.txt > "${date}.csv"
sed '1d' "${date}.csv" |sort -u|wc -l > "${date}.count"

# Clean up older (than 7 days), large .csv files.
find . -type f -name "*.csv" -mtime +7 -exec rm -f {} \;

title="Coverage as of ${date}"
num_ref=$(cat ref.count)
num_osm=$(cat ${date}.count)
percentage="$(echo "scale=2;${num_osm}*100/${num_ref}"|bc)%"
echo '{"title": "'${title}'", "percentage": "'${percentage}'", "reference": "'${num_ref}'", "osm": "'${num_osm}'"}' > progress.json

prod="/var/www/osm.vmiklos.hu/osm/housenumber-stats/hungary/"
cat progress.json > "${prod}/progress.json"
cp *.html *.js "${prod}/"

# vim:set shiftwidth=4 softtabstop=4 expandtab:
