#!/usr/bin/env bash
#
# Copyright 2020 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

cd $(dirname $0)
./overpass_query.py street-housenumbers-hungary.txt > $(date +%Y-%m-%d).csv

# vim:set shiftwidth=4 softtabstop=4 expandtab:
