(define	(problem megbizas)
	(:domain mvk)
	(:objects muhold1 - muhold muszer1 muszer2 - muszer a b c - uzemmod celpont1 celpont2 celpont3 celpont4 - celpont)
	(:init
		(vanuzemmod muszer1 a)
		(vanuzemmod muszer1 b)
		(vanuzemmod muszer2 a)
		(vanuzemmod muszer2 c)
		(vanmuszer muhold1 muszer1)
		(vanmuszer muhold1 muszer2)
		(vanaram muhold1)
		(irany muhold1 celpont1)
	)
	(:goal
		(forall (?i - celpont)
			(forall(?j - uzemmod)
				(vanfelvetel ?i ?j)
			)
		)
	)
)
