(define (domain mvk)
	(:requirements :strips :equality :typing)
	(:types muhold celpont muszer uzemmod)
	(:predicates
		(vanfelvetel ?celpont - celpont ?uzemmod - uzemmod)
		(vanmuszer ?muhold - muhold ?muszer - muszer)
		(irany ?muhold - muhold  ?celpont - celpont)
		(bekapcsolt ?muhold - muhold  ?muszer - muszer)
		(vanuzemmod ?muszer - muszer  ?uzemmod - uzemmod)
		(calibrated ?celpont - celpont ?muhold - muhold ?muszer - muszer ?uzemmod - uzemmod)
		(vanaram ?muhold - muhold)
	)
	(:action turn-to
		:parameters (?muhold  - muhold ?honnan - celpont ?hova - celpont)
		:precondition (and (exists (?y - uzemmod) (not (vanfelvetel ?hova ?y)))
			(irany ?muhold ?honnan)
			(forall(?i - uzemmod)
				(vanfelvetel ?honnan ?i))
			(not(= ?honnan ?hova))
		)
		:effect (and (irany ?muhold ?hova)
			(not (irany ?muhold ?honnan))
		)
	)
	(:action switch-on
		:parameters (?muhold - muhold ?muszer - muszer)
		:precondition (and (vanaram ?muhold)
			(not (exists (?y - muszer) (bekapcsolt ?muhold ?y))))
		:effect (bekapcsolt ?muhold ?muszer)
	)
	(:action switch-off
		:parameters (?muhold - muhold ?muszer - muszer)
		:precondition (and (vanmuszer ?muhold ?muszer)
			(bekapcsolt ?muhold ?muszer)
		)
		:effect (not (bekapcsolt ?muhold ?muszer))
	)
	(:action calibrate
		:parameters (?celpont - celpont ?muhold - muhold ?muszer - muszer ?uzemmod - uzemmod)
		:precondition (and (irany ?muhold ?celpont)
			(vanmuszer ?muhold ?muszer)
			(bekapcsolt ?muhold ?muszer)
			(vanuzemmod ?muszer ?uzemmod)
			(not (vanfelvetel ?celpont ?uzemmod))
			(forall (?i - uzemmod)
				(not(calibrated ?celpont  ?muhold  ?muszer ?i))
			)
		)
		:effect (calibrated ?celpont  ?muhold  ?muszer ?uzemmod)
	)
	(:action take-image
		:parameters (?celpont - celpont ?muhold - muhold ?muszer - muszer ?uzemmod - uzemmod)
		:precondition (and (calibrated ?celpont ?muhold  ?muszer  ?uzemmod)
			(vanmuszer ?muhold ?muszer)
			(vanuzemmod ?muszer ?uzemmod)
			(not (vanfelvetel ?celpont ?uzemmod))
		)
		:effect (and (vanfelvetel ?celpont ?uzemmod)
			(not (calibrated ?celpont ?muhold ?muszer ?uzemmod))
		)
	)
) 
