[package]
name = "github-outdated"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
home = "0.5.11"
isahc = "1.7.2"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
serde_yaml = "0.9.34"
toml = "0.8.20"
