#!/bin/bash
#
# Copyright 2022 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Wrapper around
# decrypt.key.sh from
# <https://www.cyberciti.biz/faq/use-oathtool-linux-command-line-for-2-step-verification-2fa/>.

if [ -n "$1" -a -d "$HOME/.2fa/$1" ]; then
    $HOME/.2fa/decrypt.key.sh $1
else
    cd $HOME/.2fa
    for i in *
    do
        if [ ! -d $i ]; then
            continue
        fi

        echo $i
    done
fi

# vim:set shiftwidth=4 softtabstop=4 expandtab:
