#!/bin/bash -e
# 
#   a2beamer
#  
#   Copyright (c) 2009 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

msg()
{
	echo -e "\033[1;32m==>\033[1;0m \033[1;1m$1\033[1;0m" >&2
}

txt=$1

if [ -z "$1" ]; then
	echo "usage: $0 input.txt"
	exit 1
fi

xml=$(basename $txt .txt).xml
tex=$(basename $txt .txt).tex
pdf=$(basename $txt .txt).pdf

msg "Converting from txt to xml"
asciidoc --doctype=article -b docbook $txt
msg "Converting from xml to tex"
out=$(dblatex -d -t pdf -p /etc/asciidoc/dblatex/asciidoc-dblatex.xsl -s /etc/asciidoc/dblatex/asciidoc-dblatex.sty \
	$xml 2>&1|sed -n 's/ .*//;$ p')
rm $xml
mv $out .
cd $(basename $out)
rm -f *_tmp.tex
# drop old header
sed -i '0,/secnumdepth/ d' $tex
# insert new one
sed -i '1i \
\\documentclass{beamer}\
\\setbeamertemplate{background canvas}[vertical shading][bottom=white,top=structure.fg!25]\
\\usetheme{Warsaw}\
\\setbeamertemplate{headline}{}\
\\setbeamertemplate{footline}{}\
\\setbeamersize{text margin left=0.5cm}\
\\usepackage[english]{babel}\
\\usepackage[latin1]{inputenc}\
\\usepackage{times}\
\\usepackage[T1]{fontenc}\
\\setbeamertemplate{footline}[page number]\
\\begin{document}\
' $tex
# drop old first page(s)
sed -i '/\\hypersetup/,/\\tableofcontents/ d' $tex
# insert new one
sed -i 's/\\mainmatter/\\frame{\\titlepage}/' $tex
# fix date
sed -i 's/\\renewcommand{\\DBKdate}/\\date/' $tex
# convert sections (containging enumerations) to frames
sed -i 's/\\section/\\begin{frame}[fragile]\n\\frametitle/' $tex
sed -i 's/\(\\end{itemize}\)/\1\n\\end{frame}/' $tex
# drop labels
sed -i '/\\label/d' $tex
# fix listings
sed -i 's/lstlisting/verbatim/' $tex
sed -i 's/\[firstnumber=.*,\]//' $tex
# fix images
sed -i 's|\\imgexists.*\\includegraphics\[width\(.*\)\\.*\]{.*.pdf}}}}|\\includegraphics[scale\1]|' $tex
if ls ../*.eps &>/dev/null; then
	cp ../*.eps .
fi
ln -s ~/git/vmexam/tex/Makefile .
touch $(basename $txt .txt).d
msg "Converting from tex to pdf"
if ! make &>/dev/null; then
	touch *.tex
	make
fi
mv $pdf ..
cd ..
rm -r $(basename $out)
