#!/bin/sh -e

txt=$1
xml=$(basename $txt .xml).xml
tex=$(basename $txt .txt).tex
pdf=$(basename $txt .txt).pdf

asciidoc --doctype=article -b docbook $txt
out=$(dblatex -d -t pdf -p /etc/asciidoc/dblatex/asciidoc-dblatex.xsl -s /etc/asciidoc/dblatex/asciidoc-dblatex.sty \
	$xml 2>&1|sed -n 's/ .*//;$ p')
rm $xml
mv $out .
cd $(basename $out)
rm *_tmp.tex
# drop old header
sed -i '0,/secnumdepth/ d' $tex
# insert new one
sed -i '1i \
\\documentclass{beamer}\
\\setbeamertemplate{background canvas}[vertical shading][bottom=white,top=structure.fg!25]\
\\usetheme{Warsaw}\
\\setbeamertemplate{headline}{}\
\\setbeamertemplate{footline}{}\
\\setbeamersize{text margin left=0.5cm}\
\\usepackage[english]{babel}\
\\usepackage[latin1]{inputenc}\
\\usepackage{times}\
\\usepackage[T1]{fontenc}\
\\begin{document}\
' $tex
# drop old first page(s)
sed -i '/\\hypersetup/,/\\tableofcontents/ d' $tex
# insert new one
sed -i 's/\\mainmatter/\\frame{\\titlepage}/' $tex
# fix date
sed -i 's/\\renewcommand{\\DBKdate}/\\date/' $tex
# convert sections (containging enumerations) to frames
sed -i 's/\\section/\\begin{frame}[fragile]\n\\frametitle/' $tex
sed -i 's/\(\\end{itemize}\)/\1\n\\end{frame}/' $tex
# drop labels
sed -i '/\\label/d' $tex
# fix listings
sed -i 's/lstlisting/verbatim/' $tex
sed -i 's/\[firstnumber=.*,\]//' $tex
ln -s ~/git/vmexam/tex/Makefile .
make
mv $pdf ..
cd ..
rm -r $(basename $out)
