#!/bin/bash

# This script can be symlinked as a pre-commit hook in a git repo.
# Additionally, it also supports passing in filenames as cmdline parameters, like e.g. pep8 does.

new=$(mktemp)
function finish
{
	rm -rf "$new"
}
trap finish EXIT

fix=
if [ "$1" == "--fix" ]; then
	fix=1
	shift
fi

files="$@"
if [ -z "$files" ]; then
	files="$(git diff --name-only --cached)"
fi
for file in $files
do
	if ! echo $file |grep -q '\(cxx\|cpp\|hxx\)$'; then
		continue
	fi
	astyle --options=$HOME/.astyle.options < $file > $new
	if ! diff -u $file $new; then
		if [ -n "$fix" ]; then
			cat $new > $file
			echo "Fixed the above errors."
		else
			echo "You had some style errors."
		fi
		exit 1
	fi
done
