#!/bin/bash

# Runs astyle-check on each file, which is tracked as a "my file".

cdup=$(git rev-parse --show-cdup)

[ -n "$cdup" ] && cd $cdup

for file in $(grep ';OK$' .git/myfiles.cache|sed 's/;.*//')
do
	astyle-check $file || exit 1
done
