#!/bin/bash
#
# Copyright 2025 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# This script runs openssl and mails the result if the cert will expire soon.

FULL_CHAIN=/etc/letsencrypt/live/analytics.vmiklos.hu-0001/fullchain.pem
# Write *15 here to test.
WEEK_IN_SECS=$((168*60*60))
openssl x509 -checkend $WEEK_IN_SECS -noout -in $FULL_CHAIN | grep -q 'Certificate will expire'
if [ $? -eq 0 ]; then
    echo "Your certificate will expire soon." |send-email -f "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "Cert TODO for `date +%Y%m%d`" $(git config user.email)
fi

# vim:set shiftwidth=4 softtabstop=4 expandtab:
