#!/bin/bash
#
# cgitify: look for lines in a text file which are git hashes, and turn them into cgit links
#

cgit="http://cgit.freedesktop.org/libreoffice/core/commit/?id="

if [ -z "$1" ]; then
    echo "usage: $0 <file to edit in-place> [<cgit URL>]"
    exit 1
else
    file="$1"
fi

if [ -n "$2" ]; then
    cgit="$2"
fi

sed -i "s|^\([0-9a-f]\{40\}\)|$cgit\1|" "$file"

# vim:set shiftwidth=4 expandtab:
