#!/bin/bash
#
# Copyright 2021 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Names images based on exif data, so that multiple DSC0001.jpg can be placed into a single
# directory, without manual renaming.

for i in *jpg *JPG
do
    expected="IMG_$(exiv2 "$i" 2>&1|grep -a 'Image timestamp'|sed 's/.*Image timestamp : //;s/ /_/g;s/://g;s/-//g').jpg"
    if [ "$i" != "$expected" ]; then
        if ls "$expected" &>/dev/null; then
            continue
        fi
        mv -i "$i" "$expected"
    fi
done

# vim:set shiftwidth=4 softtabstop=4 expandtab:
