#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# Write the "filename timestamp" (IMG_yyyymmdd_hhmmss) into the image file.
# Useful when e.g. the fn timestamp is sane, still Picasa considers your
# picture as taken in 1970...

for i in "$@"
do
    date=$(echo $i|sed 's/IMG_\([0-9][0-9][0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)_\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\).jpg/\1-\2-\3 \4:\5:\6/')
    exiv2 -k -v -M"set  Exif.Photo.DateTimeOriginal $date" "$i"
    exiv2 -k -v -M"set  Exif.Image.DateTime $date" "$i"
done

# vim:set shiftwidth=4 softtabstop=4 expandtab:
