#!/bin/bash

msg() {
	echo -e "\033[1;32m==>\033[1;0m \033[1;1m$1\033[1;0m" >&2
}

die() {
	echo -e "\033[1;31m==> ERROR:\033[1;0m \033[1;1m$1\033[1;0m"
	rm -rf $wd
	exit 1
}

msg "getting ics from the phone..."
echo -e 'yes\nno' |gammu --backup items.ics || die "cannot run gammu"
msg "removing invalid UTC marks..."
dos2unix items.ics
sed -i '/DTSTART/s/Z$//' items.ics
sed -i '/DTEND/s/Z$//' items.ics
sed -i '/ALARM/s/Z$//' items.ics
unix2dos items.ics
