#!/bin/bash -e

#
# example ~/.curlrc.gcalsync (use firebug to get the exact cookie/form
# values):
#
# user-agent = "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2) Gecko/20100125 Firefox/3.6"
# referer = "https://www.google.com/calendar/hosted/domain.com/render"
# cookie = "S=foo; secid=bar"
# form = "filename=@items.ics"
# form = "src=baz"
# url = "https://www.google.com/calendar/hosted/domain.com/upload_event"

echo ":: searching for the phone..."
if hcitool scan|grep -q $(grep ^port ~/.gammurc |sed 's/.*= //'); then
	echo ":: creating items.ics..."
	echo -e 'yes\nno' |gammu --backup items.ics
	echo
	dos2unix items.ics
	sed -i '/DTSTART/s/Z$//' items.ics
	sed -i '/DTEND/s/Z$//' items.ics
	sed -i '/ALARM/s/Z$//' items.ics
	unix2dos items.ics
	echo ":: uploading events..."
	curl -s -k --config ~/.curlrc.gcalsync |elinks -dump|head -n 3
	rm -f items.ics
	echo ":: done."
else
	echo ":: not found, not syncing"
fi
