#!/bin/bash -e

#
# example ~/.curlrc.gcalsync (use firebug to get the exact cookie/form
# values):
#
# user-agent = "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2) Gecko/20100125 Firefox/3.6"
# referer = "https://www.google.com/calendar/hosted/domain.com/render"
# cookie = "S=foo; secid=bar"
# form = "filename=@items.ics"
# form = "src=baz"
# url = "https://www.google.com/calendar/hosted/domain.com/upload_event"

echo ":: searching for the phone..."
if ! hcitool scan|grep -q $(grep ^port ~/.gammurc |sed 's/.*= //'); then
	echo ":: not found, not syncing"
	exit 1
fi
echo ":: contacting google.com..."
count="$((ping -c 1 www.google.com 2>/dev/null || echo ', 0 received')| grep received|sed 's/.*, \(.*\) received.*/\1/')"
if [ "$count" -eq 0 ]; then
	echo ":: google.com is not reachable, not syncing"
	exit 1
fi
echo ":: creating items.ics..."
tmp=$(mktemp -d)
cd $tmp
echo -e 'yes\nno' |gammu --backup items.ics
echo
dos2unix items.ics
sed -i '/DTSTART/s/Z$//' items.ics
sed -i '/DTEND/s/Z$//' items.ics
sed -i '/ALARM/s/Z$//' items.ics
unix2dos items.ics
echo ":: uploading events..."
out=$(curl -s -k --config ~/.curlrc.gcalsync |elinks -dump|sed -n '3p')
kdialog --title gcalsync --passivepopup "$out" 0
rm -rf $tmp
echo ":: done."
