#!/bin/bash
#
# Copyright 2025 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# This script runs git log for own commits and then filters for bugfix-like lines.

git log --author=$USER --pretty=oneline | grep '#[1-9][0-9][0-9][0-9]'

# vim:set shiftwidth=4 softtabstop=4 expandtab:
