#!/bin/bash
#
# Copyright 2019 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

# Writes exif captions to a jpeg file from a captions text file. Useful in case
# you prefer writing your captions offline, then put them into the images, so
# online services like picasa can extract them (using e.g. digikam).
#
# Usage: insert-exif-comments <captions.txt>.
#
# Format of captions.txt is:
#
# DSC_2805.JPG foo
# DSC_2806.JPG bar baz
# DSC_2807.JPG
#
# If the caption is empty, then no caption is written to the file.

IFS="
"
cat $1 | while read line
do
	file="${line%% *}" # Content till the first space.
	comment="${line#* }" # Remaining content.
	if [ "$file" == "$comment" -o ! -e $file ]; then
		continue
	fi
	exiv2 -M"set Exif.Photo.UserComment $comment" $file
done

# vim:set shiftwidth=4 softtabstop=4 expandtab:
