#!/bin/bash
#
# Copyright 2019 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#

#
# Instead of killing a given process, kill its parent, but with the same flags.
#

# Original PID.
last=${@:$#}

# Look up parent PID.
parent=$(grep ^PPid /proc/$last/status|sed 's/.*:.//')

# Delete the last argument.
n=$(($#-1))
set -- ${@:1:$n}

exec kill "$@" $parent

# vim:set shiftwidth=4 softtabstop=4 expandtab:
