#!/bin/bash -e
#
# Copyright 2022 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#
# Renders a markdown file with Python and opens it in a browser. This has the benefit that it's the
# same implementation as what Pelican uses, if you use that for blog purposes.
#
# If you want to test how it would look like on GitHub, then
# <https://jbt.github.io/markdown-editor/> is a better tool.

html="$(echo $1 |sed 's/md$/html/')"
python3 -m markdown --extension tables $1 > $html
firefox $html

# vim:set shiftwidth=4 softtabstop=4 expandtab:
