#!/bin/bash
#
# Copyright 2022 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#
# offlineimap was python2-only, so use mbsync and notmuch instead.

while true
do
    mbsync collabora && break
done
notmuch new

# vim:set shiftwidth=4 softtabstop=4 expandtab:
