#!/bin/bash
#
# Copyright 2022 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# offlineimap was python2-only, so use mbsync and notmuch instead.

mbsync collabora
notmuch new

# vim:set shiftwidth=4 softtabstop=4 expandtab:
