#!/bin/bash
#
# Copyright 2021 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Trivial wrapper around a cmdline, sends a note about its exit code.
# Config file:
#
# access_token='...'
# room_url='https://server.example.com:8448/_matrix/client/r0/rooms/!roomhash:example.com'
#
# Create the access token using:
# curl -X POST -d '{"type":"m.login.password", "user":"...", "password":"..."}' "https://server.example.com:8448/_matrix/client/r0/login"
#
# The 'pushping' name refers to <https://www.pushbullet.com/>, which provides something similar, but
# not with your self-hosted matrix instance.

"$@"
exit_code=$?
source ~/.config/pushpingrc
if [ ${exit_code} == 0 ]; then
    result="passed"
else
    result="failed"
fi
escaped_home="${HOME//\\\//\\\\//}"
working_directory=${PWD/$escaped_home/\~}
curl \
    -s \
    -X POST \
    -d "{\"msgtype\":\"m.text\", \"body\":\"$*: $result, host: $HOST, working directory: $working_directory, exit code: $exit_code\"}" \
    -o /dev/null \
    "$room_url/send/m.room.message?access_token=$access_token"
exit ${exit_code}

# vim:set shiftwidth=4 softtabstop=4 expandtab:
