#!/bin/bash
#
# Copyright 2022 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Downscales a bitmap (scanned document) to 96x96 DPI to avoid huge PDFs and then converts the
# result to PDF.
#
# Example usage: scan-document ~/Downloads/<date>.jpg receipt1.pdf

downscaled=$(mktemp --suffix=.jpg)
convert $1 $downscaled
convert $downscaled $2
rm $downscaled

# vim:set shiftwidth=4 softtabstop=4 expandtab:
