#!/bin/bash

# Runs astyle-check/pycodestyle/etc on each file, which is tracked as an "indented file".

cdup=$(git rev-parse --show-cdup)

[ -n "$cdup" ] && cd $cdup

fix=
if [ "$1" == "--fix" ]; then
	fix=y
	shift
fi

for file in $(cat .git/indented-files2.cache)
do
	case $file in
	*.cxx|*.cpp|*.hxx)
		find-unsorted-includes $file || exit 1
		# Use css:: instead.
		grep -H -n using.*com::sun::star:: $file && exit 1
		;;
	*.py)
		pycodestyle --ignore=E501 $file || exit 1

		if echo $file |grep -q /uitest/; then
			continue
		fi

		lint=$(pylint $file 2>/dev/null | egrep -i 'unused|indent')
		if [ -n "$lint" ]; then
			echo "$file"
			echo "$lint"
			exit 1
		fi
		;;
	*)
		echo "unexpected extension for file: $file"
		exit 1
	;;
	esac
done

exit 0
