#!/bin/bash

# Runs astyle-check/pep8/etc on each file, which is tracked as an "indented file".

cdup=$(git rev-parse --show-cdup)

[ -n "$cdup" ] && cd $cdup

for file in $(cat .git/indented-files.cache)
do
	case $file in
	*.cxx|*.hxx)
		astyle-check $file || exit 1
		;;
	*.py)
		pep8 $file || exit 1

		lint=$(pylint $file 2>/dev/null | egrep -i 'unused|indent')
		if [ -n "$lint" ]; then
			echo "$file"
			echo "$lint"
			exit 1
		fi
		;;
	*)
		echo "unexpected extension for file: $file"
		exit 1
	;;
	esac
done
