#!/bin/bash
#
# Copyright 2019 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

#
# This is a simple script to be invoked by cron to get the temperature/humidity
# of a sensor like
# <https://ha.privateeyepi.com/store/index.php?route=product/product&path=66&product_id=127>
# e.g. 2 times on an hour.
#

cd $(dirname $0)

# Get just the year.
year="$(date +%Y)"
# Get ISO8601 date.
dateTime="$(date -Iseconds)"
csv="${year}.csv"

if [ ! -e "${csv}" ]; then
    echo "date-time,temperature,humidity" > ${csv}
fi

data="$(curl -s -f http://192.168.0.118/temp 2>&1)"
ret=$?
if [ ${ret} != 0 ]; then
    today="$(date +%Y%m%d)"
    # Send email only once a day.
    if ! grep -q "${today}" errors.log; then
        echo "Error code ${ret}" |~/bin/pymail -r "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "thermodump error for ${today}" $(git config user.email)
        echo "${today}" >> errors.log
    fi
    exit
fi

# Strip 'NA,' prefix.
data=$(echo ${data}|sed 's/NA,//')

echo "${dateTime},${data}" >> ${csv}

# vim:set shiftwidth=4 softtabstop=4 expandtab:
