[package]
name = "ics2txt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ical = "0.11.0"
time = { version = "0.3.41", features = ["formatting", "local-offset", "parsing"] }
time-tz = "2.0.0"
