#!/bin/bash
#
# Copyright 2021 Miklos Vajna. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

mydir="$(dirname $0)"
if [ -h "$0" ]; then
    mydir="$(dirname "$(readlink -f "$0")")"
fi

arg="$1"
if [ -n "$arg" ]; then
    arg="$(realpath "$1")"
fi

$mydir/exec_client.py \
    "c:/program files (x86)/microsoft office/root/office16/winword.exe" \
    "$arg"

# vim:set shiftwidth=4 softtabstop=4 expandtab:
