name: tests
on:
  push:
    branches-ignore:
      - 'private/**'
  pull_request:
    branches-ignore:
      - 'private/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          components: rustfmt, clippy, llvm-tools-preview
          default: true
      - name: Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-1.75.0-${{ hashFiles('**/Cargo.toml') }}
      - name: Run make check
        run: |
          tools/ci-build.sh
